package com.mycompany.myapp.domain.enumeration;

/**
 * The NomFiliere enumeration.
 */
public enum NomFiliere {
    AGRI_ELEVAGE,
    AGRICULTURE,
    PECHE,
    ELEVAGE,
    MINE_CARRIERES,
    ARTISANAT,
    BATIMAT_TRAVAUX_PUBLIQUES,
    MECANIQUE,
    MENUISERIE_BOIS,
    HABILLEMENT,
    AGROALIMENTAIRE,
    ELECTROTECHNIQUE_ELECTRIQUE_ENERGETIQUE,
    HYDRAULIQUE,
    STRUCTURE_METALLIQUE,
    STRUCTURE_PLASTIQUE,
    BEAUTE_ESTHETIQUE,
    DEVELOPPEMENT_TERRITORIAL,
    DROIT,
    ECONOMIE_GESTION_COMMERCE_LOGISTIQUE,
    INSDUSTRIE_CULTURELLE_ET_CREATIVE,
    INFORMATIQUE_ET_NUMERIQUE,
    RESTAURATION_ET_HOTELLORIE,
    SANTE_BIOLOGIE_CHIMIE,
    SPORT,
    TOURISME,
    ENVIRONNEMENT,
    AUTRES,
}
