export enum NomFiliere {
  AGRI_ELEVAGE = 'AGRI_ELEVAGE',

  AGRICULTURE = 'AGRICULTURE',

  PECHE = 'PECHE',

  ELEVAGE = 'ELEVAGE',

  MINE_CARRIERES = 'MINE_CARRIERES',

  ARTISANAT = 'ARTISANAT',

  BATIMAT_TRAVAUX_PUBLIQUES = 'BATIMAT_TRAVAUX_PUBLIQUES',

  MECANIQUE = 'MECANIQUE',

  MENUISERIE_BOIS = 'MENUISERIE_BOIS',

  HABILLEMENT = 'HABILLEMENT',

  AGROALIMENTAIRE = 'AGROALIMENTAIRE',

  ELECTROTECHNIQUE_ELECTRIQUE_ENERGETIQUE = 'ELECTROTECHNIQUE_ELECTRIQUE_ENERGETIQUE',

  HYDRAULIQUE = 'HYDRAULIQUE',

  STRUCTURE_METALLIQUE = 'STRUCTURE_METALLIQUE',

  STRUCTURE_PLASTIQUE = 'STRUCTURE_PLASTIQUE',

  BEAUTE_ESTHETIQUE = 'BEAUTE_ESTHETIQUE',

  DEVELOPPEMENT_TERRITORIAL = 'DEVELOPPEMENT_TERRITORIAL',

  DROIT = 'DROIT',

  ECONOMIE_GESTION_COMMERCE_LOGISTIQUE = 'ECONOMIE_GESTION_COMMERCE_LOGISTIQUE',

  INSDUSTRIE_CULTURELLE_ET_CREATIVE = 'INSDUSTRIE_CULTURELLE_ET_CREATIVE',

  INFORMATIQUE_ET_NUMERIQUE = 'INFORMATIQUE_ET_NUMERIQUE',

  RESTAURATION_ET_HOTELLORIE = 'RESTAURATION_ET_HOTELLORIE',

  SANTE_BIOLOGIE_CHIMIE = 'SANTE_BIOLOGIE_CHIMIE',

  SPORT = 'SPORT',

  TOURISME = 'TOURISME',

  ENVIRONNEMENT = 'ENVIRONNEMENT',

  AUTRES = 'AUTRES',
}
