export enum Secteur {
  SANTE = 'SANTE',

  BATIMENT = 'BATIMENT',

  ELECTRICITE = 'ELECTRICITE',

  ELEVAGE_PECHE = 'ELEVAGE_PECHE',

  COUTURE = 'COUTURE',

  COIFFURE = 'COIFFURE',

  AGROALIMENTAIRE = 'AGROALIMENTAIRE',

  AGRICULTURE = 'AGRICULTURE',

  TOURISME = 'TOURISME',

  GESTION_DE_LA_FAUNE_ET_DE_LA_FLORE = 'GESTION_DE_LA_FAUNE_ET_DE_LA_FLORE',

  GENIE_RURAL = 'GENIE_RURAL',

  ARTISANAT = 'ARTISANAT',

  Autres = 'Autres',
}
